busybox: fix build error due to speed_table patches
Build fails with following:
| libbb/speed_table.c:12:0: warning: "B1500000" redefined
|  #define B1500000
|
| In file included from build/tmp/work/armv7vehf-neon-poky-linux-gnueabi/busybox/1.27.2-r0/recipe-sysroot/usr/include/termios.h:39:0,
|                  from include/libbb.h:52,
|                  from libbb/speed_table.c:10:
| build/tmp/work/armv7vehf-neon-poky-linux-gnueabi/busybox/1.27.2-r0/recipe-sysroot/usr/include/bits/termios.h:164:0: note: this is the location of the previous definition
|  #define  B1500000 0010012
|
| libbb/speed_table.c:90:11: error: expected expression before ',' token
|   {B1500000, 1500000/200 + 0x8000u},

Note that I have truncated paths in above error message.

It seems that B1500000 is all ready defined in termios.h so dropped that part from the patch

Signed-off-by: Mirza Krak <mirza.krak@endian.se>